#!/bin/sh
set -e

if command -v deb-systemd-helper >/dev/null 2>&1; then
    deb-systemd-helper enable carnine-frontend.service >/dev/null || true
fi

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if command -v deb-systemd-invoke >/dev/null 2>&1; then
    deb-systemd-invoke start carnine-frontend.service >/dev/null || true
fi

exit 0